name: Clean InfinityFree File Manager

on:
  workflow_dispatch:  # Allows manual trigger for cleaning

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Clean Target Directory on InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.username }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Required, but no files will be uploaded
        server-dir: /aiyouthalliance.tech/htdocs/  # Target directory to clean
        dry-run: false  # Ensure actual execution
        dangerous-clean-slate: true  # Deletes all files in the server-dir
