name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Create Backup (backup.tar.gz)
        run: |
          # Create a backup of all files in the current directory, excluding the backup file itself
          tar --exclude='./backup.tar.gz' -czvf backup.tar.gz .

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Upload everything from the local directory
          exclude: backup.tar.gz
          protocol: ftps  # Use secure FTPS (or plain FTP if required)
          sync-mode: true # Enable sync mode to overwrite files
