name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Step 3: Install PHP dependencies
      - name: Install dependencies
        run: composer install

      # Step 4: Backup current files locally (exclude `.git/` and `backup.tar.gz`)
      - name: Create Backup (backup.tar.gz)
        run: |
          # Exclude `.git/` directory and the backup file itself from the archive
          tar --exclude='./.git' --exclude='./backup.tar.gz' -czvf backup.tar.gz .
        # This ensures `.git/` and the backup file are not included in the archive.

      # Step 5: Clean remote directory (dangerous-clean-slate)
      - name: Clean up remote FTP directory
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true

      # Step 6: Deploy new files to FTP server
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Upload all files from the current directory
          exclude: backup.tar.gz  # Exclude the backup file
