name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        # Version Check: Using actions/checkout v3 for stability and latest features.

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        # Version Check: Using shivammathur/setup-php v2 for PHP environment setup.

      # Step 3: Install PHP dependencies
      - name: Install dependencies
        run: composer install

      # Step 4: Create a backup of the current directory
      - name: Create Backup (backup.tar.gz)
        run: |
          # Create a backup of all files in the current directory, excluding the backup file itself
          tar --exclude='./backup.tar.gz' -czvf backup.tar.gz .
        # Note: Backup ensures data recovery in case of issues during deployment.

      # Step 5: Deploy files to FTP server
      - name: Deploy via FTP (Overwrite)
        uses: sebastianpopp/ftp-action@v0.1.0
        with:
          host: ${{ secrets.FTP_HOST }}       # FTP server address
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          local-dir: ./                         # Upload all files from the local directory
          remote-dir: /home/aiyoutha/domains/aiyouthalliance.tech/public_html
          exclude: backup.tar.gz                # Exclude the backup file
          overwrite: true                       # Ensure files are overwritten on the server
        # Version Check: Using sebastianpopp/ftp-action v0.1.0 for FTP deployment.
